### ISSUE TITLE
使用VSCode编译工程出现error在vcruntime.h文件

### ISSUE THREAD

**Issue by zukunftnetz** [lilongww/OpenVisa#2]
![vcruntime h_error](https://github.com/lilongww/OpenVisa/assets/40055320/6a25fbee-e662-4730-bef4-72445d67d71a)

**Comment by lilongww** [comment]
我很少使用vscode，你可以尝试使用vs2022看看是否存在同样问题，我后面有空时会使用vscode试试

**Comment by zukunftnetz** [comment]
![image](https://github.com/lilongww/OpenVisa/assets/40055320/60d51ae9-1ec1-4abb-bb15-b46cb371f7bc)
用VS2022编译出现如图错误，请问是boost库安装错误码

**Comment by lilongww** [comment]
Boost库应当按照README.md中的描述配置环境变量，boost库可以到 https://sourceforge.net/projects/boost/files/boost-binaries/ 下载预编译好的，vs2022 x64对应boost库的应当下载  [boost_1_85_0-msvc-14.3-64.exe](https://sourceforge.net/projects/boost/files/boost-binaries/1.85.0/boost_1_85_0-msvc-14.3-64.exe/download)

**Comment by lilongww** [comment]
注意，如果你已经打开了VS，然后再配置环境变量，那么你应当重新启动VS，因为windows应用程序仅在启动时读取环境变量。

**Comment by zukunftnetz** [comment]
![image](https://github.com/lilongww/OpenVisa/assets/40055320/0be92ea0-51a7-49c8-8019-38e7d39f5c3e)
VSCode编译部分正常了，Test目录的几个还是编译不成功，而且没办法运行

**Comment by lilongww** [comment]
编译Test需要gtest库，如果你已经编译出OpenVisa.dll则无需关心，如果你仅仅想尝试使用OpenVisa，可以去 https://gitee.com/llongww/OpenVisaApplication 的发行版下载可执行程序。

**Comment by lilongww** [comment]
不想编译Tests，可以将 BUILD_TEST 选项置为OFF

**Comment by zukunftnetz** [comment]
![image](https://github.com/lilongww/OpenVisa/assets/40055320/7df0a365-c6ce-43a7-a531-c1db6243cd47)
请问这是编译成功了吗？在我的项目中如何使用OpenVisad.dll呢？

**Comment by lilongww** [comment]
参考Example或 [OpenVisaApplication](https://gitee.com/llongww/OpenVisaApplication)
